name: update demo

on:
  workflow_dispatch:

jobs:
  update-demo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4.2.1
        with:
          go-version-file: go.mod

      - uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/demo.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update demo
          body: ${{ github.sha }}
          branch: docs/update-demo
          branch-suffix: short-commit-hash
